### ISSUE TITLE
Remaining adapter sequences 

### ISSUE THREAD

**Issue by cnk113** [SchulzLab/Aeron#13]
Hello,

I was wondering if the inputs can handle adapter sequences between the fused transcripts without too much problems?

Thanks,
Chang

**Comment by SchulzLab** [comment]
Dear Chang,
I don't understand how there could be adapter sequences between the fused transcripts. The adapters are added to the transcripts that are being sequenced, and the hypothesis of fusion transcripts is, that these transcript exist in the cell due to biological mechanisms, such as translocation in a cancer cell.

Therefore, I don't think that your case can happen. Or do you have some other datasource in mind?

Hope that helps,
Marcel

**Comment by cnk113** [comment]
Ah well I'm looking to see if it can detect chimeric PCR transcripts and to see if it can map both (or more) transcripts with an adapter sequence in between.

**Comment by SchulzLab** [comment]
I see. Well AERON allows for a large number of sequencing errors so if there was a short adapter at either end of the chimeric read, it may be able to find that.
You could simulate the case you have in mind and see whether AERON finds it. We have not tested it for this task.
